### ISSUE TITLE
网页推理直接运行会报错

### ISSUE THREAD

**Issue by 12915494174** [CrazyBoyM/llama3-Chinese-chat#7]
按照README.md文件直接打开界面，提问报了错误如下图：
![image](https://github.com/CrazyBoyM/llama3-Chinese-chat/assets/68487349/4dddd600-a796-4c7c-b0cc-1ea12a978490)
日志：
![image](https://github.com/CrazyBoyM/llama3-Chinese-chat/assets/68487349/ccc09477-a3bf-4be4-b5df-7e72b71f6a57)
`root@autodl-container-30634997bd-fb05be27:~/llama3-Chinese-chat# streamlit run deploy/web_streamlit_for_instruct.py /root/autodl-tmp/llama-3-8b-Instruct-chinese_v2 --theme.base="dark"

Collecting usage statistics. To deactivate, set browser.gatherUsageStats to false.

  You can now view your Streamlit app in your browser.

  Network URL: http://172.17.0.13:8501
  External URL: http://116.172.94.216:8501

load model...
Loading checkpoint shards:   0%|                                                                                                                                                                        | 0/2 [00:00<?, ?it/s]/root/miniconda3/lib/python3.10/site-packages/torch/_utils.py:831: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.03s/it]
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
load model end.
load model...
load model end.
load model...
load model end.
/root/llama3-Chinese-chat/deploy/web_streamlit_for_instruct.py:80: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
  logger.warn(  # pylint: disable=W4902
--- Logging error ---
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/root/miniconda3/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/root/miniconda3/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/root/miniconda3/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/root/miniconda3/lib/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "/root/miniconda3/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/root/miniconda3/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 306, in _run_script_thread
    self._run_script(request.rerun_data)
  File "/root/miniconda3/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 584, in _run_script
    exec(code, module.__dict__)
  File "/root/llama3-Chinese-chat/deploy/web_streamlit_for_instruct.py", line 314, in <module>
    main(model_name_or_path, adapter_name_or_path)
  File "/root/llama3-Chinese-chat/deploy/web_streamlit_for_instruct.py", line 288, in main
    for cur_response in generate_interactive(
  File "/root/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/root/llama3-Chinese-chat/deploy/web_streamlit_for_instruct.py", line 80, in generate_interactive
    logger.warn(  # pylint: disable=W4902
Message: "Both 'max_new_tokens' (=8192) and 'max_length'(=8392) seem to have been set. 'max_new_tokens' will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)"
Arguments: (<class 'UserWarning'>,)
2024-04-22 15:05:59.625 Uncaught app exception
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 584, in _run_script
    exec(code, module.__dict__)
  File "/root/llama3-Chinese-chat/deploy/web_streamlit_for_instruct.py", line 314, in <module>
    main(model_name_or_path, adapter_name_or_path)
  File "/root/llama3-Chinese-chat/deploy/web_streamlit_for_instruct.py", line 288, in main
    for cur_response in generate_interactive(
  File "/root/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "/root/llama3-Chinese-chat/deploy/web_streamlit_for_instruct.py", line 120, in generate_interactive
    model_inputs = model.prepare_inputs_for_generation(
  File "/root/miniconda3/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 1267, in prepare_inputs_for_generation
    past_length, past_length + position_ids.shape[-1], device=position_ids.device
AttributeError: 'NoneType' object has no attribute 'shape'`

**Comment by 12915494174** [comment]
可以了，transformers==4.40.0正常跑了。
